version: 2
updates:
  - package-ecosystem: github-actions
    directories: ["/", "/.github/actions/*"]
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    groups:
      actions:
        patterns: ["*"]
  - package-ecosystem: pub
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    groups:
      pub:
        patterns: ["*"]
