# dev_tool templates/rust/bacon.toml @1.0.0
default_job = "check"

[jobs.check]
command = ["cargo", "check", "--color", "always", "--workspace", "--all-targets", "--all-features"]
need_stdout = false

[jobs.clippy]
command = ["cargo", "lint"]
need_stdout = false

[jobs.test]
command = ["cargo", "test-all", "--color", "always"]
need_stdout = true

[jobs.doc]
command = ["cargo", "doc-check", "--color", "always"]
need_stdout = false
